(function(){
'use strict';
const p=new URLSearchParams(location.search);
if(location.pathname!=='/teacher'||p.get('projector')!=='1')return;
const images={'פילגש בגבעה ומלחמת בנימין':'/01-giva-benjamin.png','פילוג הממלכה – רחבעם וירבעם':'/02-split-kingdom.png','המאבק החשמונאי הפנימי':'/03-hasmonean-conflict.png','חורבן בית שני – קמצא ובר קמצא והמאבקים בירושלים':'/04-second-temple.png','אלטלנה':'/05-altalena.png','מלחמת לבנון הראשונה':'/06-first-lebanon-war.png','רצח רבין':'/07-rabin-assassination.png','ההתנתקות מגוש קטיף':'/08-disengagement.png'};
const revealed=new Set();const root=document.getElementById('projectorRoot');if(!root)return;
function enhance(card){if(card.classList.contains('empty')||card.dataset.storyEnhanced==='1')return;const top=card.querySelector('.projector-card-top');const titleEl=top&&top.querySelector('h3');const numEl=top&&top.querySelector('.projector-card-num');if(!titleEl||!numEl)return;const title=titleEl.textContent.trim();const group=numEl.textContent.trim();const image=images[title];if(!image)return;const answers=card.innerHTML;card.dataset.storyEnhanced='1';card.dataset.storyGroup=group;card.classList.add('story-projector-card');card.tabIndex=0;card.setAttribute('role','button');const cover=`<div class="story-cover"><img src="${image}" alt="תמונה מייצגת: ${title}"><div class="story-cover-shade"></div><div class="story-cover-copy"><div class="story-group-badge">קבוצה ${group}</div><h3>${title}</h3><div class="story-tap-hint">לחצו לחשיפת תשובות הקבוצה</div></div></div>`;function paint(){const open=revealed.has(group);card.classList.toggle('story-revealed',open);card.setAttribute('aria-label',open?`קבוצה ${group}, ${title}. לחצו לחזרה לתמונה`:`קבוצה ${group}, ${title}. לחצו לחשיפת התשובות`);card.innerHTML=open?`${answers}<div class="story-back-hint">לחצו לחזרה לתמונה</div>`:cover;}function toggle(){if(revealed.has(group))revealed.delete(group);else revealed.add(group);paint();}card.onclick=toggle;card.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle();}};paint();}
function enhanceAll(){root.querySelectorAll('.projector-card').forEach(enhance);}const observer=new MutationObserver(()=>requestAnimationFrame(enhanceAll));observer.observe(root,{childList:true,subtree:true});enhanceAll();
})();
