(function(){
'use strict';
const app=document.getElementById('app');
const p=new URLSearchParams(location.search);
const path=location.pathname;
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
const teacherUrl=(code,token)=>location.origin+'/teacher?code='+encodeURIComponent(code)+'&token='+encodeURIComponent(token);
async function access(body){const r=await fetch('/api/access',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let d={};try{d=await r.json();}catch(e){}if(!r.ok){const er=new Error(d.error||'request');er.code=d.error;throw er;}return d;}
function storeTeacher(code,token){const u=teacherUrl(code,token);try{localStorage.setItem('brothers-forget-last-room',u);localStorage.setItem('brothers-forget-last-code',code);}catch(e){}return u;}
function msg(code){const map={bad_pin:'קוד המורה צריך להכיל 4–6 ספרות.',bad_code:'קוד הכיתה צריך להכיל 6 ספרות.',room_not_found:'לא נמצאה כיתה עם הקוד הזה.',invalid_credentials:'קוד הכיתה או קוד המורה אינם נכונים.',pin_not_set:'הכיתה הזו נוצרה לפני מנגנון השמירה. פתחו אותה מהקישור המקורי והגדירו קוד מורה.',too_many_attempts:'בוצעו יותר מדי ניסיונות. המתינו כמה דקות ונסו שוב.'};return map[code]||'לא הצלחנו להשלים את הפעולה. נסו שוב.';}
function hero(){return `<section class="hero"><div class="eyebrow">אני ישראלי · מחלוקת והבית המשותף</div><h1>כשאחים שוכחים</h1><p>ניהול מחלוקות בעם</p><div class="question">איך מנהלים מחלוקת קשה מבלי לפרק את הבית המשותף?</div></section>`;}
function renderAccessHome(){
 let recent='';try{recent=localStorage.getItem('brothers-forget-last-room')||'';}catch(e){}
 app.innerHTML=`<div class="shell">${hero()}<div class="access-intro"><div><strong>ניהול כיתה נשמר אוטומטית</strong><span>אותו קוד כיתה יכול ללוות אתכם גם במפגש הבא.</span></div><div class="access-saved-badge">שמירה עד 30 יום מהפעילות האחרונה</div></div><div class="grid two access-grid"><section class="card access-card"><div class="access-icon">＋</div><h2>כיתה חדשה</h2><p class="muted">צרו חדר חדש ובחרו קוד מורה אישי. התלמידים יקבלו רק את קוד הכיתה.</p><div class="field"><label for="accessClassName">שם הכיתה — לא חובה</label><input id="accessClassName" maxlength="60" placeholder="לדוגמה: י׳2"></div><div class="field"><label for="accessNewPin">קוד מורה אישי</label><input id="accessNewPin" class="access-pin" type="password" inputmode="numeric" autocomplete="new-password" maxlength="6" placeholder="4–6 ספרות"><div class="tiny">הקוד נדרש רק למורה, כדי לחזור לכיתה ממחשב אחר.</div></div><div id="newRoomError" class="access-error"></div><button class="btn pri access-main-btn" id="accessCreate">יצירת כיתה חדשה</button></section><section class="card access-card"><div class="access-icon">↩</div><h2>המשך כיתה קיימת</h2><p class="muted">חזרו לכל התשובות, ההצבעות והשלב שבו עצרתם.</p><div class="field"><label for="accessRoomCode">קוד כיתה</label><input id="accessRoomCode" class="access-code" inputmode="numeric" maxlength="6" placeholder="6 ספרות"></div><div class="field"><label for="accessResumePin">קוד מורה</label><input id="accessResumePin" class="access-pin" type="password" inputmode="numeric" autocomplete="current-password" maxlength="6" placeholder="4–6 ספרות"></div><div id="resumeRoomError" class="access-error"></div><button class="btn soft access-main-btn" id="accessResume">המשך כיתה קיימת</button>${recent?'<div class="access-divider"><span>או</span></div><button class="btn ghost access-main-btn" id="accessRecent">פתיחת הכיתה האחרונה במכשיר זה</button>':''}</section></div><section class="card access-note"><strong>מה נשמר?</strong><span>תשובות הקבוצות, ענן המילים, אמנת המחלוקת, מד החום, תוצאות והשלב הפעיל — הכול נשאר באותו חדר.</span></section></div>`;
 document.getElementById('accessCreate').onclick=async()=>{const b=document.getElementById('accessCreate'),err=document.getElementById('newRoomError');err.textContent='';const pin=(document.getElementById('accessNewPin').value||'').trim();const className=(document.getElementById('accessClassName').value||'').trim();if(!/^\d{4,6}$/.test(pin)){err.textContent=msg('bad_pin');return;}b.disabled=true;b.textContent='יוצר כיתה…';try{const d=await access({action:'create',className,pin});location.href=storeTeacher(d.code,d.teacherToken);}catch(e){err.textContent=msg(e.code);b.disabled=false;b.textContent='יצירת כיתה חדשה';}};
 document.getElementById('accessResume').onclick=async()=>{const b=document.getElementById('accessResume'),err=document.getElementById('resumeRoomError');err.textContent='';const code=(document.getElementById('accessRoomCode').value||'').trim();const pin=(document.getElementById('accessResumePin').value||'').trim();if(!/^\d{6}$/.test(code)){err.textContent=msg('bad_code');return;}if(!/^\d{4,6}$/.test(pin)){err.textContent=msg('bad_pin');return;}b.disabled=true;b.textContent='פותח כיתה…';try{const d=await access({action:'resume',code,pin});location.href=storeTeacher(d.code,d.teacherToken);}catch(e){err.textContent=msg(e.code);b.disabled=false;b.textContent='המשך כיתה קיימת';}};
 if(recent)document.getElementById('accessRecent').onclick=()=>location.href=recent;
}
function teacherLink(code,token){return teacherUrl(code,token);}
function pinDialog(code,token){
 const old=document.getElementById('teacherPinOverlay');if(old)old.remove();const o=document.createElement('div');o.id='teacherPinOverlay';o.className='access-overlay';o.innerHTML=`<div class="access-dialog"><button class="access-dialog-close" id="pinDialogClose">×</button><div class="eyebrow">גישה למורה</div><h2>הגדרת קוד מורה</h2><p class="muted">בחרו 4–6 ספרות שתוכלו לזכור. הקוד לא יוצג לתלמידים.</p><div class="field"><input id="teacherPinInput" type="password" inputmode="numeric" maxlength="6" placeholder="4–6 ספרות"></div><div id="teacherPinError" class="access-error"></div><button class="btn pri" id="teacherPinSave">שמירת קוד המורה</button></div>`;document.body.appendChild(o);const close=()=>o.remove();document.getElementById('pinDialogClose').onclick=close;o.onclick=e=>{if(e.target===o)close();};document.getElementById('teacherPinSave').onclick=async()=>{const b=document.getElementById('teacherPinSave'),pin=(document.getElementById('teacherPinInput').value||'').trim(),err=document.getElementById('teacherPinError');err.textContent='';if(!/^\d{4,6}$/.test(pin)){err.textContent=msg('bad_pin');return;}b.disabled=true;b.textContent='שומר…';try{await access({action:'setPin',code,teacherToken:token,pin});b.textContent='נשמר ✓';setTimeout(close,650);}catch(e){err.textContent=msg(e.code);b.disabled=false;b.textContent='שמירת קוד המורה';}};
}
function injectTeacherAccess(){if(path!=='/teacher'||p.get('projector')==='1')return;const code=p.get('code')||'',token=p.get('token')||'';if(!code||!token)return;try{storeTeacher(code,token);}catch(e){}const first=document.querySelector('.shell > .card:first-child');if(!first||document.getElementById('teacherAccessBar'))return;const bar=document.createElement('div');bar.id='teacherAccessBar';bar.className='teacher-access-bar';bar.innerHTML=`<div class="teacher-access-state"><span class="teacher-access-dot">✓</span><div><strong>הכיתה נשמרת אוטומטית</strong><small>אפשר לחזור אליה עם קוד הכיתה וקוד המורה.</small></div></div><div class="teacher-access-actions"><button class="btn ghost" id="copyTeacherLink">העתקת קישור מורה</button><button class="btn ghost" id="changeTeacherPin">הגדרת / שינוי קוד מורה</button></div>`;const strip=first.querySelector('.stage-strip');if(strip)strip.before(bar);else first.appendChild(bar);document.getElementById('copyTeacherLink').onclick=async()=>{try{await navigator.clipboard.writeText(teacherLink(code,token));const b=document.getElementById('copyTeacherLink');const t=b.textContent;b.textContent='הקישור הועתק ✓';setTimeout(()=>{if(b)b.textContent=t;},1200);}catch(e){}};document.getElementById('changeTeacherPin').onclick=()=>pinDialog(code,token);}
if(path==='/'||path===''){renderAccessHome();}else if(path==='/teacher'&&p.get('projector')!=='1'){injectTeacherAccess();new MutationObserver(injectTeacherAccess).observe(app,{childList:true,subtree:true});setTimeout(()=>access({action:'touch',code:p.get('code')||'',teacherToken:p.get('token')||''}).catch(()=>{}),700);}
})();
